version: "3.7"

services:
  server:
    image: adguard/adguardhome:v0.107.46
    container_name: adguardhome
    hostname: adguard
    restart: on-failure
    ports:
      #  DNS
      - 53:53/tcp
      - 53:53/udp
      # Setup Interface
      - 3000:3000/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # DNS-over-QUIC
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
    volumes:
      - ${APP_DATA_DIR}/data/adguardhome/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/adguardhome/conf:/opt/adguardhome/conf
