version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: adguard-home_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: adguard/adguardhome:v0.107.46
    restart: on-failure
    ports:
      #  DNS
      - 53:53/tcp
      - 53:53/udp
      # Setup/Admin Interface
      - 3001:3000/tcp
      # HTTP
      - 80:80/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # DNS-over-QUIC
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
    volumes:
      - ${APP_DATA_DIR}/data/adguardhome/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/adguardhome/conf:/opt/adguardhome/conf
